### ISSUE TITLE
Fatal: Error: Unknown Policy LRU (issue when Cache is on)

### ISSUE THREAD

**Issue by j19861986** [diladele/squid3-windows#37]
I have just installed squid again
I have problem when cache is on
It says it has a "Fatal: Error: Unknown policy lru"

**Comment by ea-at-diladele-com** [comment]
Hi. Do you have the following lines in your squid.conf?

cache_replacement_policy heap LRU
memory_replacement_policy heap LRU 

Thank you!

**Comment by j19861986** [comment]
I have just changed the lines you wrote replaced with Heap LFUDA
(cache_replacement_policy heap LFUDA
memory_replacement_policy heap LFUDA)
The problem is still there
Is there other configurations that still use lru?

**Comment by ea-at-diladele-com** [comment]
Does it work without enabling the cache? could you please attach the log file and your squid.conf? I will have a look at it in more detail later during the day. Thank you!

P.S. you can send the files to support@diladele.com

**Comment by j19861986** [comment]
Squid works without Cache is on
But I like to have the cache on
Can you maybe configure with lru enabled? (Dunno how to deactivate lru in squid.conf)

**Comment by ea-at-diladele-com** [comment]
I will have a look and will recompile with support of both heap and lru. Thanks!

**Comment by ea-at-diladele-com** [comment]
One more thing - you removed your old cache and recreated it, correct?

**Comment by j19861986** [comment]
I removed it and ran "squid -z" still said unknown

**Comment by ea-at-diladele-com** [comment]
I have pushed the fix to the sources, the official MSI will be tomorrow evening or so (CET time). Thank you!

**Comment by ra-at-diladele-com** [comment]
Done; build on site
Please check and close the bug if it now works

**Comment by ea-at-diladele-com** [comment]
j19861986, did you have a chance to ckeck? does it work for you now? thank you!

**Comment by j19861986** [comment]
I have checked it worked... but then I looked at log, 256 max file descriptors...

**Comment by j19861986** [comment]
I mean now i can use it.
If i fast browse, it can be a little pain, it doesn't work. (maxfd)

**Comment by ea-at-diladele-com** [comment]
Could you please confirm that you see this line in the log at the beginning
"With 3200 file descriptors available "?   - so config has max_filedescriptors set to 3200

but then you still see the error regarding 256 descriptors afterwards?

we are using setrlimit function of Cygwin to enable more descriptors per process, maybe it does not work as expected. I will have a look at this over the weekend.

I would also appreciate if you could send me your log at support@diladele.com

Thank you very much!

**Comment by j19861986** [comment]
I think it is hardcoded
I have also tried with conf file set max file descriptors
It can't get over the hard coded (compiled)
it says -- 2015/05/22 08:31:48 kid1| With 256 file descriptors available --

**Comment by ea-at-diladele-com** [comment]
Hmm, I look into the log and see only 256. I just tried a couple of minutes ago on my machine and it is 3200 - the max value.

Do you have the following line in your config?

max_filedescriptors 3200

**Comment by j19861986** [comment]
I mean it must be compiled with the option "--with-max-fd="

**Comment by ea-at-diladele-com** [comment]
it is compiled with 65 thousand. you can check it running squid -v

**Comment by ea-at-diladele-com** [comment]
Mine has this 
2015/05/22 12:22:57 kid1| With 3200 file descriptors available

**Comment by j19861986** [comment]
oh, the numbers must be written in conf...
I can't remember how I compiled old old version that override the default setting

**Comment by j19861986** [comment]
it works, the final build is with 65 thousand?
I think I will soon get that
The one i have here has 3200 max

**Comment by ea-at-diladele-com** [comment]
The problem is Cygwin/Windows. It is not possible to use more than 3200 descriptors on my machine for example, even though the squid is compiled with 65000. In order to support that - Cygwin itself should be recompiled I suppose.
The problem is that some Posix functionality on Cygwin is not yet properly support.


Could you test a little bit more, trying you "fast browsing"?
I am not sure that setrlimit actually solved the issue even though it says 3200 available.

Thanks a lot for the feedback and testing effort!



Really appreciate your time and feedback.

**Comment by j19861986** [comment]
I think I it has to be compiled with --with maxfd=
But cannot remember what extra I had put on, in cygwin.
I have compiled squid in cygport with 65536

**Comment by j19861986** [comment]
The one you have compiled says nothing with max

**Comment by j19861986** [comment]
Sry it came so late
I couldn't see the compile option, I did today

**Comment by ea-at-diladele-com** [comment]
np :)
if after testing you do not see the problem with descriptors again, I would appreciate if you could close the issue.

Thanks a lot and have a nice day!
